export const AUTH_STATE_CHANGE = 'AUTH_STATE_CHANGE';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const CHANGE_DARK_MODE = 'CHANGE_DARK_MODE';
export const GET_CLASSMATES = 'GET_CLASSMATES';
export const GET_LEADERBOARD = 'GET_LEADERBOARD';
export const GET_CHALLENGER = 'GET_CHALLENGER';
